#ifndef IMAGEIDENTIFIERS_HPP
#define IMAGEIDENTIFIERS_HPP

enum Image {
    UNDEFINED,

    HELLO_WORLD,
    PLAYER,
    GRASS,
    SMALL_TREE,
    PLAYER_V2,

    PLAYER_V3_FRONT,
    PLAYER_V3_BACK,
    PLAYER_V3_LEFT,
    PLAYER_V3_RIGHT,

    PLAYER_V3_FRONT_RUN1,
    PLAYER_V3_FRONT_RUN2,
    PLAYER_V3_FRONT_RUN3,
    PLAYER_V3_FRONT_RUN4,

    BLOODSPLATTER_1_1,
    BLOODSPLATTER_1_2,
    BLOODSPLATTER_1_3,
    BLOODSPLATTER_1_4,
    BLOODSPLATTER_1_5,
    BLOODSPLATTER_1_6,
    BLOODSPLATTER_1_7,
    BLOODSPLATTER_1_8,
    BLOODSPLATTER_1_9,
    BLOODSPLATTER_1_10,
    BLOODSPLATTER_1_11,

    YELLOW_FLOWER,
    GREEN_FLOWER,
    VIOLET_FLOWER,
    BLUE_FLOWER,

    TEST_SQUARE_10x10,
    TEST_SQUARE_1x1,

    STONE_1,
    WATER
};

#endif //IMAGEIDENTIFIERS_HPP
