#ifndef MESSAGETYPES_HPP
#define MESSAGETYPES_HPP

enum MESSAGE_TYPE {
    OUTDATED,
    CONNECT,
    DISCONNECT,
    INPUTDATA,
    MOVECOMPONENTS,
    RENDERCOMPONENTS,
    MOVECOMPONENTSDIFF,
    RENDERCOMPONENTSDIFF,
    PLAY_SOUND,
    REGISTER_ID_TO_SYSTEM,
    REMOVE_ID,
    REMOVE_ID_FROM_SYSTEM,
    REMOVE_ID_FROM_SYSTEMS,
    ACTIVATE_ID
};

#endif //MESSAGETYPES_HPP
