#ifndef SYSTEMIDENTIFIERS_HPP
#define SYSTEMIDENTIFIERS_HPP

enum System {
    ANIMATION,
    ATTACK,
    CAMERA,
    COLLISION,
    HASHGRID_SIZE,
    HASHGRID_TEXTURE,
    HEALTH,
    INPUT,
    KEYBOARD,
    MOVEDIFF,
    MOVE,
    REMOVE,
    RENDERDIFF,
    RENDER,
    SERVERNETWORK,
};

#endif //SYSTEMIDENTIFIERS_HPP
